### ISSUE TITLE
Add support for NGSI polling mode to receive updates

### ISSUE THREAD

**Issue by justb4** [wirecloud-fiware/ngsi-source-operator#4]
In some cases, for example when the WireCloud server is running on a different server/domain than the Orion CB, a callback subscription mode is not always possible. In those cases a polling mode may be applied. At the rate of a user-specified interval the `ngsi-source-operator` will query the OCB. Possibly with some restrictions like a single type and a minimum interval time. Polling mode (boolean) and interval may be specified via the config.xml.

In the longer term a "long polling mode" may be considered, as described here: https://www.pubnub.com/blog/2014-12-01-http-long-polling or even full COMET (https://en.wikipedia.org/wiki/Comet_(programming)).

Alternatively a new Operator like `ngsi-polling-operator` may be defined for this mode.

**Comment by aarranz** [comment]
> In some cases, for example when the WireCloud server is running on a different server/domain than the Orion CB, a callback subscription mode is not always possible.

Can you elaborate this a bit more? All the examples provided in FIWARE Lab match that scenario, the Mashup portal is hosted in one server and the context broker is hosted in other server. Moreover, they are in different domains (https://mashup.lab.fiware.org and http://orion.lab.fiware.org:1026, respectively)

Take into account that, currently, subscriptions are handled using a [NGSI-proxy](https://github.com/conwetlab/ngsijs/tree/master/ngsi-proxy), this solves almost all the problems, if not all, regarding NAT and cross-domain.

> In those cases a polling mode may be applied. At the rate of a user-specified interval the ngsi-source-operator will query the OCB. Possibly with some restrictions like a single type and a minimum interval time. Polling mode (boolean) and interval may be specified via the config.xml.

I think is better to talk about those details after analysing if this polling mode is needed. Anyway, in my opinion, the real problem is that the operator will have to detect changes in the entities and this will be a heavy operation. Probably would be better to limit the number of entities than limiting the filtering...

> In the longer term a "long polling mode" may be considered, as described here: https://www.pubnub.com/blog/2014-12-01-http-long-polling or even full COMET (https://en.wikipedia.org/wiki/Comet_(programming)).

This cannot be accomplished without changes in the API currently provided by the Context Broker. The other options is to create a intermediate service for providing that comet endpoint. I guess the Orion team is no going to be interested in such comet endpoint as they are working on providing notifications using websockets.

> Alternatively a new Operator like ngsi-polling-operator may be defined for this mode.

We'll see :)

**Comment by justb4** [comment]
On 06-11-15 20:18, Álvaro Arranz wrote:

> ```
> In some cases, for example when the WireCloud server is running on a
> different server/domain than the Orion CB, a callback subscription
> mode is not always possible.
> ```
> 
> Can you elaborate this a bit more? All the examples provided in FIWARE
> Lab match that scenario, the Mashup portal is hosted in one server and
> the context broker is hosted in other server. Moreover, they are in
> different domains (https://mashup.lab.fiware.org and
> http://orion.lab.fiware.org, respectively)
> Well, the main problem is that I cannot get subscriptions to work. In my 
> setup I run IoTAgentCpp with Orion using docker-compose on my own 
> server. WC is run on mashup.lab.fiware.org. This all works fine: 
> Operators like NGSI Browser requests data, Entity2POI shows POI on 
> MapWidget etc. Only I cannot get the NGSISource operator, thus NGSI 
> Subscriptions to work:
- I see that the subscription request is handled ok at my Orion instance 
  and in main.js
- on changing the Entity (via UL2.0) I see that my OCB instance posts a 
  notification callback to the ngsiproxy.lab.fiware.org (port 443 see 
  below) though it does not seem to get a response...
- the server has no NAT but straight inet connectivity, though it 
  originates from 'localhost' (as OCB is running in Docker).
  
     myip.45965-130.206.081.241.00443: POST 
  /callbacks/18:35:03-1:18:35:04-1 HTTP/1.1
     User-Agent: orion/0.24.0-next libcurl/7.19.7
     Host: ngsiproxy.lab.fiware.org:443
     fiware-service: fiwareiot
     X-Auth-Token: XXXX
     Accept: application/xml, application/json
     Content-length: 1644
     Content-type: application/json; charset=utf-8
  
    {
     "subscriptionId" : "563f7945cbe043e2d20f5cf1",
     "originator" : "localhost",
     "contextResponses" : [

**Comment by aarranz** [comment]
I tested your workspace, and I can confirm you that the problem is that your context broker installation is missing [Rush](http://fiware-orion.readthedocs.org/en/develop/admin/rush/index.html). Currently, orion need rush for being able to send https notifications, your dashboard is working when using the NGSI-proxy available at `http://ngsiproxy.lab.fiware.org` :)

![captura de pantalla 2015-11-08 a las 18 34 41](https://cloud.githubusercontent.com/assets/841201/11021610/9d784d9c-8647-11e5-9200-69e7c463308f.png)

The main problem when using the http version of the NGSI-proxy is that it is treated as a security problem by browsers when the main web page is served using https (as in this case, where the Mashup portal is served using https). You can [bypass this problem](http://247support.custhelp.com/app/answers/detail/a_id/11736/~/chrome-and-firefox%3A-blocked-mixed-%28https-and-http%29-content), but the correct way to fix this is to enable https notifications in the Orion Context Broker.

I never tried to install rush when using the docker version of the context broker, so I cannot help you too much in this task. I think that the best option is to create a question using the `fiware-orion` tag in StatckOverflow.

**Comment by justb4** [comment]
Update: got Rush with Orion working for https://mashup.lab.fiware.org/justb4/NGSI%20Subscription and now notifications via https are working! Setting this up within the Orion Docker image was a bit involved, but would be nice to create an extended Orion Docker image with Rush embedded. 

See documentation how this was setup (second Mashup example):
http://sospilot.readthedocs.org/en/latest/fiware.html#temperature-in-poi-on-map

We can close this issue, but the above Rush-setup info may be of use at some place in the Fiware documentation. Maybe StackOverflow. But possibly first make an extended Docker Orion-Rush image.
